"""Natural language → AttentionJob spec, via one headless Sonnet call.

Cost contract (the load-bearing design decision): the LLM runs HERE, once,
at creation time. It never runs on the dispatcher tick. A compiled job is
plain data — it keeps firing correctly with the LLM offline, and an idle job
costs nothing.

Safety contract: the model's output is untrusted. It is parsed as JSON,
checked against the live registries, and condition expressions go through
`conditions.validate()` before anything is stored. The model can only
select from registered triggers/actions/signals — there is no code path
where its text is evaluated.

The capability catalogue in the prompt is generated by
`describe_registries()`, so registering a new trigger/action/signal
automatically teaches the compiler about it. Prompt and registry cannot
drift.
"""

from __future__ import annotations

import asyncio
import json
import logging
import re
import subprocess
from datetime import datetime, timedelta, timezone

from attention.registry import ACTIONS, TRIGGERS, describe_registries

logger = logging.getLogger("orchestrator.attention")

COMPILE_TIMEOUT_SECONDS = 90

# Compilation is interactive — the user is staring at a spinner — so allow a
# little more parallelism than the background prompt slots.
_COMPILE_SLOTS = asyncio.Semaphore(2)


class CompileError(RuntimeError):
    """The request could not be turned into a valid job."""


# The job schema and scheduling rules are shared verbatim between the two
# prompts (one-shot /compile and conversational /chat) so a fix to a rule —
# like the daily_at wall-clock exception — can never apply to one entry
# path and not the other.
JOB_SCHEMA = """\
{
  "kind": "reminder" | "watch" | "digest" | "automation",
  "title": "<= 80 chars, imperative, what the user will see in a list",
  "trigger_type": "<one of the TRIGGERS below>",
  "trigger_config": { ... matching that trigger's schema ... },
  "action_type": "<one of the ACTIONS below>",
  "action_config": { ... matching that action's schema ... },
  "confirm": "<one sentence, second person, stating exactly what will happen and when>"
}"""

SCHEDULING_RULES = """\
1. Absolute timestamps ("at", "start_at", "until") are ISO-8601 UTC. Resolve
   every relative phrase ("in an hour", "tomorrow morning", "tonight")
   against NOW below. The ONE exception is "daily_at", which is a LOCAL
   wall-clock HH:MM — for "every morning at 9" write "09:00", never the UTC
   equivalent.
2. Prefer the simplest trigger that satisfies the request. A one-off
   reminder is "at". Something repeating is "every". "Tell me when X
   happens" is "signal".
3. For "when <agent> makes progress / responds / finishes / is done", use
   trigger_type "signal" with
     {"signal": "agent.is_generating", "op": "became", "value": false}
   That is the end-of-turn edge and fires exactly once per completed turn.
   Do NOT use op "changed" on agent.last_message_at for this: it fires on
   every intermediate message inside one turn and produces a push storm.
4. "when it breaks / errors" is
   {"signal": "agent.status", "op": "became", "value": "ERROR"}.
   Prefer "became" over "changed" for every user-facing watch — "changed"
   fires on transitions in BOTH directions and on every intermediate value.
   Reserve "changed" for genuinely any-movement requests.
5. Only reference an agent_id / task_id / project that appears in the
   CONTEXT block. Never invent one.
6. Default action is "notify". Use "run_prompt" ONLY when the user asks for
   a summary, digest, analysis or report — it spends tokens on every fire.
7. "kind" is for grouping in the UI only. Pick the closest label.
8. "confirm" must be verifiable by the user at a glance and must state the
   resolved local time in a friendly form when a time is involved."""

SYSTEM_RULES = f"""\
You compile a user's natural-language request into ONE scheduling job for a
developer tool called Xylocopa, which runs many Claude Code agents.

Output ONLY a single JSON object. No prose, no markdown fences, no preamble.

Schema:
{JOB_SCHEMA}

Rules:
{SCHEDULING_RULES}
9. If the user names an agent that is not in CONTEXT, or the request is
   impossible with the listed capabilities, or too ambiguous to compile
   safely, output exactly:
   {{"error": "<one short sentence explaining what you need>"}}
"""

CHAT_RULES = f"""\
You are the attention assistant of Xylocopa, a developer tool that runs many
Claude Code agents. You appear as a small orange orb in the corner of the
screen and talk through a tiny speech bubble. You can chat, answer questions
about the user's agents and pending jobs, and schedule jobs (reminders,
agent watches, digests, automations).

Output ONLY a single JSON object. No prose, no markdown fences, no preamble:
{{
  "say": "<your reply — short, warm, at most ~200 characters, plain text>",
  "job": null | <a job object matching the JOB SCHEMA below>
}}

JOB SCHEMA:
{JOB_SCHEMA}

Conversation rules:
1. Mirror the user's language: if they write Chinese, "say" is Chinese.
2. The bubble is tiny — one to two short sentences, no markdown, no lists.
   At most one emoji.
3. Attach a "job" ONLY when the user asked for something schedulable AND you
   have every detail you need. "say" then restates what will happen and
   when; the UI renders Create/Cancel buttons under it, so never ask the
   user to type yes.
4. If a detail is missing or ambiguous (which agent? what time?), set job to
   null and ask ONE specific question in "say". CONTEXT lists what exists —
   never invent an agent or project.
5. For questions ("what can you do", "what's pending", "which agents are
   running") answer from CAPABILITIES and CONTEXT with job null. Pending
   jobs are listed in CONTEXT; you cannot edit or delete them — the user
   does that from the jobs list in this bubble.
6. Off-topic chat gets a friendly one-liner and, when natural, a nudge back
   to what you can do. Never invent facts about the system.

Scheduling rules (for the "job" object):
{SCHEDULING_RULES}
"""


def _now_block() -> str:
    now_utc = datetime.now(timezone.utc)
    now_local = datetime.now()
    tz_name = now_local.astimezone().tzname() or "local"
    offset_min = int(round(
        (now_local - now_utc.replace(tzinfo=None)).total_seconds() / 60,
    ))
    return (
        f"NOW (UTC):   {now_utc.replace(microsecond=0).isoformat()}\n"
        f"NOW (local): {now_local.replace(microsecond=0).isoformat()} "
        f"({tz_name}, UTC{offset_min // 60:+03d}:{abs(offset_min) % 60:02d})"
    )


def _build_prompt(text: str, context: str) -> str:
    return (
        f"{SYSTEM_RULES}\n"
        f"{_now_block()}\n\n"
        f"CAPABILITIES\n{describe_registries()}\n\n"
        f"CONTEXT\n{context or '(no agents or projects supplied)'}\n\n"
        f"USER REQUEST\n{text}\n"
    )


def build_context(db, *, limit: int = 25) -> str:
    """Compact roster of things the user could plausibly refer to.

    Column reads only — this runs on an interactive request. Includes ids
    because rule 5 forbids the model from inventing them.
    """
    from models import Agent, Project

    lines: list[str] = ["Agents (id · project · name · status · unread):"]
    agents = (
        db.query(Agent)
        .filter(Agent.is_subagent == False)  # noqa: E712
        .filter(Agent.status != "STOPPED")
        .order_by(Agent.last_message_at.desc().nullslast())
        .limit(limit)
        .all()
    )
    if agents:
        for a in agents:
            lines.append(
                f"  {a.id} · {a.project} · {a.name} · {a.status.value} · {a.unread_count}"
            )
    else:
        lines.append("  (none)")

    projects = db.query(Project.name).limit(60).all()
    if projects:
        lines.append("Projects: " + ", ".join(p[0] for p in projects))
    return "\n".join(lines)


def build_jobs_context(db, *, limit: int = 20) -> str:
    """The user's pending jobs, so the chat can answer "what have I set up?".

    Chat-only: the one-shot compile prompt never needs them, and keeping its
    prompt byte-stable protects the behavior the confirm-preview tests pin.
    """
    from models import AttentionJob

    jobs = (
        db.query(AttentionJob)
        .filter(AttentionJob.status.in_([
            AttentionJob.STATUS_ACTIVE, AttentionJob.STATUS_PAUSED,
            AttentionJob.STATUS_ERROR,
        ]))
        .order_by(
            AttentionJob.next_run_at.asc().nullslast(),
            AttentionJob.created_at.desc(),
        )
        .limit(limit)
        .all()
    )
    if not jobs:
        return "Pending jobs: (none)"
    lines = ["Pending jobs (title · trigger · status · next run UTC):"]
    for j in jobs:
        nxt = j.next_run_at.replace(microsecond=0).isoformat() if j.next_run_at else "-"
        lines.append(f"  {j.title} · {j.trigger_type} · {j.status} · {nxt}")
    return "\n".join(lines)


def _claude_p(prompt: str) -> tuple[int, str, str]:
    from config import ATTENTION_MODEL, CLAUDE_BIN
    from route_helpers import subprocess_clean_env

    proc = subprocess.run(
        [CLAUDE_BIN, "-p", "-", "--output-format", "text",
         "--no-session-persistence", "--model", ATTENTION_MODEL],
        input=prompt,
        capture_output=True, text=True,
        timeout=COMPILE_TIMEOUT_SECONDS,
        cwd="/tmp",
        env=subprocess_clean_env(),
    )
    return proc.returncode, proc.stdout, proc.stderr


def _extract_json(raw: str) -> dict:
    """Pull the JSON object out of the model's reply.

    Tolerates the two failure modes seen from `claude -p` in this codebase:
    a ```json fence, and a sentence before the object. Anything else is a
    hard error — we do not guess.
    """
    text = (raw or "").strip()
    if not text:
        raise CompileError("the assistant returned nothing")

    fence = re.search(r"```(?:json)?\s*(.+?)\s*```", text, re.S)
    if fence:
        text = fence.group(1).strip()

    try:
        obj = json.loads(text)
    except ValueError:
        start, end = text.find("{"), text.rfind("}")
        if start < 0 or end <= start:
            raise CompileError(f"could not parse a job from: {text[:160]}")
        try:
            obj = json.loads(text[start:end + 1])
        except ValueError:
            raise CompileError(f"could not parse a job from: {text[:160]}")

    if not isinstance(obj, dict):
        raise CompileError("the assistant did not return a JSON object")
    return obj


def validate_spec(spec: dict) -> dict:
    """Check a compiled spec against the live registries.

    Also called on hand-authored specs from the API, so the LLM path and the
    explicit-form path share exactly one validation gate.
    """
    from attention.conditions import ConditionError, validate as validate_condition

    if "error" in spec:
        raise CompileError(str(spec["error"])[:300])

    trigger_type = spec.get("trigger_type")
    if trigger_type not in TRIGGERS:
        raise CompileError(
            f"unknown trigger {trigger_type!r} — expected one of {', '.join(TRIGGERS)}"
        )
    action_type = spec.get("action_type")
    if action_type not in ACTIONS:
        raise CompileError(
            f"unknown action {action_type!r} — expected one of {', '.join(ACTIONS)}"
        )

    trigger_config = spec.get("trigger_config") or {}
    action_config = spec.get("action_config") or {}
    if not isinstance(trigger_config, dict) or not isinstance(action_config, dict):
        raise CompileError("trigger_config and action_config must be objects")

    if trigger_type == "signal":
        condition = trigger_config.get("condition")
        if not isinstance(condition, dict):
            raise CompileError("a signal trigger needs a 'condition' object")
        try:
            validate_condition(condition)
        except ConditionError as exc:
            raise CompileError(str(exc))

    if trigger_type == "at":
        raw_at = trigger_config.get("at")
        parsed = _parse_iso(raw_at)
        if parsed is None:
            raise CompileError(f"could not read a time from {raw_at!r}")
        # A compiler that resolves "in an hour" into the past is the most
        # likely silent failure, so reject it rather than firing instantly.
        floor = datetime.now(timezone.utc).replace(tzinfo=None) - timedelta(minutes=1)
        if parsed <= floor:
            raise CompileError(
                f"that resolves to {parsed.isoformat()}Z, which is in the past"
            )

    title = (spec.get("title") or "").strip()
    if not title:
        raise CompileError("the assistant produced no title")

    kind = spec.get("kind") or "reminder"
    if kind not in ("reminder", "watch", "digest", "automation"):
        kind = "reminder"

    return {
        "kind": kind,
        "title": title[:300],
        "trigger_type": trigger_type,
        "trigger_config": trigger_config,
        "action_type": action_type,
        "action_config": action_config,
        "confirm": (spec.get("confirm") or title)[:400],
    }


def preview_first_run(spec: dict) -> str | None:
    """The instant this spec would actually first fire, as naive-UTC ISO.

    Computed by the trigger itself rather than read out of the model's prose.
    That distinction matters: the `confirm` sentence is generated text and can
    disagree with the config it describes (a UTC/local mix-up in `daily_at`
    reads as a plausible sentence while scheduling the wrong hour). The UI
    shows THIS value, so the user is always confirming the real schedule.
    """
    trigger = TRIGGERS.get(spec.get("trigger_type", ""))
    if trigger is None:
        return None
    now = datetime.now(timezone.utc).replace(tzinfo=None)
    try:
        first = trigger.initial(spec.get("trigger_config") or {}, now)
    except Exception:
        logger.warning("attention: preview failed for %s", trigger.name, exc_info=True)
        return None
    if first is None:
        return None
    if first.tzinfo is not None:
        first = first.replace(tzinfo=None)
    return first.isoformat()


def _parse_iso(raw) -> datetime | None:
    if isinstance(raw, datetime):
        return raw.replace(tzinfo=None) if raw.tzinfo else raw
    if not isinstance(raw, str) or not raw.strip():
        return None
    try:
        dt = datetime.fromisoformat(raw.strip().replace("Z", "+00:00"))
    except ValueError:
        return None
    return dt.astimezone(timezone.utc).replace(tzinfo=None) if dt.tzinfo else dt


async def compile_request(text: str, db) -> dict:
    """Compile `text` into a validated job spec. Raises CompileError.

    Returns the spec plus a "confirm" sentence — the caller shows that to
    the user for approval before persisting. A silently mis-parsed reminder
    time is the failure mode this preview exists to catch.
    """
    text = (text or "").strip()
    if not text:
        raise CompileError("say what you want me to do")
    if len(text) > 2000:
        raise CompileError("that request is too long — keep it under 2000 characters")

    prompt = _build_prompt(text, build_context(db))

    async with _COMPILE_SLOTS:
        try:
            rc, out, err = await asyncio.to_thread(_claude_p, prompt)
        except subprocess.TimeoutExpired:
            raise CompileError(
                f"the assistant timed out after {COMPILE_TIMEOUT_SECONDS}s — try again"
            )
        except FileNotFoundError:
            raise CompileError("the claude CLI is not available on this host")

    if rc != 0:
        logger.warning("attention compile failed rc=%d: %s", rc, (err or "")[:300])
        raise CompileError("the assistant could not be reached — try again")

    spec = validate_spec(_extract_json(out))
    spec["source_text"] = text
    # Authoritative first-fire time, so the confirmation the user approves
    # reflects the trigger's arithmetic rather than the model's description
    # of it.
    spec["preview_next_run_at"] = preview_first_run(spec)
    logger.info(
        "attention: compiled %r → %s × %s (first run %s)",
        text[:60], spec["trigger_type"], spec["action_type"],
        spec["preview_next_run_at"],
    )
    return spec


# ---------------------------------------------------------------------------
# Conversational entry point
# ---------------------------------------------------------------------------

# History the model sees. Enough for a clarify → answer → confirm exchange;
# a longer memory adds tokens per turn without adding scheduling accuracy.
MAX_CHAT_TURNS = 16
MAX_CHAT_CHARS = 2000


async def chat_request(messages: list[dict], db) -> dict:
    """One conversational turn. Returns {"say": str, "spec": dict | None}.

    Same cost contract as compile_request — one Sonnet call, at interaction
    time only — but with the recent transcript in the prompt, so "which
    agent?" → "the camera one" works. A proposed job is validated through
    the exact gate /compile uses; nothing here is persisted. A job that
    fails validation degrades to conversation (the say + the validator's
    complaint) instead of a hard error, because mid-chat a 422 would
    read as the assistant going silent.
    """
    turns: list[tuple[str, str]] = []
    for m in (messages or [])[-MAX_CHAT_TURNS:]:
        role = "USER" if (m.get("role") == "user") else "ASSISTANT"
        content = str(m.get("content") or "").strip()
        if content:
            turns.append((role, content[:MAX_CHAT_CHARS]))
    if not turns or turns[-1][0] != "USER":
        raise CompileError("say something first")

    convo = "\n".join(f"{role}: {content}" for role, content in turns)
    prompt = (
        f"{CHAT_RULES}\n"
        f"{_now_block()}\n\n"
        f"CAPABILITIES\n{describe_registries()}\n\n"
        f"CONTEXT\n{build_context(db)}\n{build_jobs_context(db)}\n\n"
        f"CONVERSATION\n{convo}\n\n"
        f"Reply with the single JSON object now.\n"
    )

    async with _COMPILE_SLOTS:
        try:
            rc, out, err = await asyncio.to_thread(_claude_p, prompt)
        except subprocess.TimeoutExpired:
            raise CompileError(
                f"the assistant timed out after {COMPILE_TIMEOUT_SECONDS}s — try again"
            )
        except FileNotFoundError:
            raise CompileError("the claude CLI is not available on this host")

    if rc != 0:
        logger.warning("attention chat failed rc=%d: %s", rc, (err or "")[:300])
        raise CompileError("the assistant could not be reached — try again")

    obj = _extract_json(out)
    say = str(obj.get("say") or "").strip()[:600]
    job = obj.get("job")

    spec = None
    if isinstance(job, dict):
        try:
            spec = validate_spec(job)
            spec["source_text"] = turns[-1][1]
            spec["preview_next_run_at"] = preview_first_run(spec)
        except CompileError as exc:
            # The model proposed something the registries reject. Surface the
            # reason in-conversation so the user can rephrase.
            spec = None
            reason = str(exc)[:200]
            say = f"{say} ({reason})" if say else reason

    if not say and spec is None:
        raise CompileError("the assistant returned nothing useful")
    if not say:
        say = spec.get("confirm") or "Here is what I can set up:"

    logger.info(
        "attention: chat turn (%d msgs) → say=%r spec=%s",
        len(turns), say[:60],
        f"{spec['trigger_type']}×{spec['action_type']}" if spec else None,
    )
    return {"say": say, "spec": spec}
